INSERT INTO category(name) VALUES ('Agriculture');
INSERT INTO category(name) VALUES ('Apparel, Made-Ups & Home Furnishing');
INSERT INTO category(name) VALUES ('Automotive');
INSERT INTO category(name) VALUES ('Beauty & Wellness');
INSERT INTO category(name) VALUES ('Banking, Financial Services and Insurance');
INSERT INTO category(name) VALUES ('Construction');
INSERT INTO category(name) VALUES ('Electronics & Hardware');
INSERT INTO category(name) VALUES ('Furniture & Fittings');
INSERT INTO category(name) VALUES ('Gems & Jewellery');
INSERT INTO category(name) VALUES ('Green Jobs');
INSERT INTO category(name) VALUES ('Healthcare');
INSERT INTO category(name) VALUES ('Hydrocarbons');
INSERT INTO category(name) VALUES ('Instrumentation, Automation, Surveillance and Communication');
INSERT INTO category(name) VALUES ('IT-ITES');
INSERT INTO category(name) VALUES ('Life Sciences');
INSERT INTO category(name) VALUES ('Logistics');
INSERT INTO category(name) VALUES ('Management and Entrepreneurship & Professional');
INSERT INTO category(name) VALUES ('Media & Entertainment');
INSERT INTO category(name) VALUES ('Plumbing');
INSERT INTO category(name) VALUES ('Power');
INSERT INTO category(name) VALUES ('Retail');
INSERT INTO category(name) VALUES ('Rubber');
INSERT INTO category(name) VALUES ('Strategic Manufacturing');
INSERT INTO category(name) VALUES ('Telecom');
INSERT INTO category(name) VALUES ('Textiles & Handlooms');
INSERT INTO category(name) VALUES ('Tourism & Hospitality');
INSERT INTO category(name) VALUES ('People with Disability');
INSERT INTO category(name) VALUES ('Management - Security');
INSERT INTO category(name) VALUES ('Other');
INSERT INTO category(name) VALUES ('Employability Enhancer');
INSERT INTO category(name) VALUES ('Instructional / Learning Strategies');

INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Rebbecca','Didio',381749123,'rebbecca.didio@didio.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Stevie','Hallo',799973366,'stevie.hallo@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Mariko','Stayer',855589019,'mariko_stayer@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Gerardo','Woodka',260444682,'gerardo_woodka@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Mayra','Bena',214556085,'mayra.bena@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Idella','Scotland',878681355,'idella@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Sherill','Klar',865228931,'sklar@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Ena','Desjardiws',252269402,'ena_desjardiws@desjardiws.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Vince','Siena',731849989,'vince_siena@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Theron','Jarding',868904661,'tjarding@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Amira','Chudej',781353271,'amira.chudej@chudej.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Marica','Tarbor',311746817,'marica.tarbor@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Shawna','Albrough',779776039,'shawna.albrough@albrough.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Paulina','Maker',883448929,'paulina_maker@maker.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Rose','Jebb',749419471,'rose@jebb.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Reita','Tabar',235187078,'rtabar@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Maybelle','Bewley',793877293,'mbewley@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Camellia','Pylant',251714345,'camellia_pylant@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Roy','Nybo',253117778,'rnybo@nybo.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Albert','Sonier',793542612,'albert.sonier@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Hayley','Taghon',216384380,'htaghon@taghon.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Norah','Daleo',253226127,'ndaleo@daleo.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Rosina','Sidhu',764604488,'rosina_sidhu@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Royal','Costeira',753386357,'royal_costeira@costeira.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Barrie','Nicley',364432786,'bnicley@nicley.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Linsey','Gedman',747853781,'lgedman@gedman.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Laura','Bourbonnais',365436688,'laura.bourbonnais@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Fanny','Stoneking',737219123,'fstoneking@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Kristian','Ellerbusch',827481250,'kristian@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Gwen','Julye',370636734,'gjulye@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Ben','Majorga',281719051,'ben.majorga@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Trina','Oto',711538567,'trina@oto.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Emelda','Geffers',870973947,'emelda.geffers@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Zana','Ploszaj',779918880,'zana_ploszaj@ploszaj.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Shaun','Rael',389985485,'shaun.rael@rael.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Oren','Lobosco',250461307,'olobosco@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Catherin','Aguele',764761399,'caguele@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Pearlene','Boudrie',744637223,'pboudrie@boudrie.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Kathryn','Bonalumi',830712258,'kathryn.bonalumi@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Suzan','Landa',715761412,'suzan.landa@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Sommer','Agar',891303372,'sagar@agar.net.au');

INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (4,'M','AADHAAR',807049207654,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (5,'M','AADHAAR',807049207655,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (6,'M','AADHAAR',807049207656,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (7,'M','AADHAAR',807049207657,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (8,'M','AADHAAR',807049207658,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (9,'M','AADHAAR',807049207659,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (10,'M','AADHAAR',807049207660,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (11,'M','AADHAAR',807049207661,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (12,'M','AADHAAR',807049207662,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (13,'M','AADHAAR',807049207663,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (14,'M','AADHAAR',807049207664,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (15,'M','AADHAAR',807049207665,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (16,'M','AADHAAR',807049207666,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (17,'M','AADHAAR',807049207667,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (18,'M','AADHAAR',807049207668,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (19,'M','AADHAAR',807049207669,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (20,'M','AADHAAR',807049207670,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (21,'M','AADHAAR',807049207671,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (22,'M','AADHAAR',807049207672,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (23,'M','AADHAAR',807049207673,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (24,'M','AADHAAR',807049207674,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (25,'M','AADHAAR',807049207675,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (26,'M','AADHAAR',807049207676,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (27,'M','AADHAAR',807049207677,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (28,'M','AADHAAR',807049207678,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (29,'M','AADHAAR',807049207679,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (30,'M','AADHAAR',807049207680,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (31,'M','AADHAAR',807049207681,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (32,'M','AADHAAR',807049207682,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (33,'M','AADHAAR',807049207683,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (34,'M','AADHAAR',807049207684,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (35,'M','AADHAAR',807049207685,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (36,'M','AADHAAR',807049207686,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (37,'M','AADHAAR',807049207687,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (38,'M','AADHAAR',807049207688,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (39,'M','AADHAAR',807049207689,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (40,'M','AADHAAR',807049207690,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (41,'M','AADHAAR',807049207691,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (42,'M','AADHAAR',807049207692,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (43,'M','AADHAAR',807049207693,20,0,0,0,0);
INSERT INTO student(id,gender,id_proof,id_number,age,counselling,exams_percentage,interview,placement) VALUES (44,'M','AADHAAR',807049207694,20,0,0,0,0);
