INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('praveeen','reddy','praveeenreddy@gmail.com',9895967968,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('bala','showry','balashowry@gmail.com',9997627269,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('jay','kumari','jaykumari@gmail.com',9949841485,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('sudheer','raj','sudheerraj@gmail.com',9950707760,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('sam','ruth','samruth@gmail.com',9915331253,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('swapna','kumari','swapnakumari@gmail.com',9949525353,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('ishaan','raj','ishaanraj@gmail.com',9899541142,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('bala','sunder','balasunder@gmail.com',9984821228,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('dilip','pravi','dilippravi@gmail.com',9967123671,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('harsha','modu','harshamodu@gmail.com',9926908828,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('ganesh','varanasi','ganeshvaranasi@gmail.com',9971477669,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('damodar','alla','damodaralla@gmail.com',9935781900,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('prasad','pasa','prasadpasa@gmail.com',9924912129,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('neeraj','reddy','neerajreddy@gmail.com',9999696962,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('ranjith','yeryva','ranjithyeryva@gmail.com',9897152722,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('siva','vadlamudi','siva vadlamudi@gmail.com',9908446717,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('katepalli','hemanth','katepallihemanth@gmail.com',9955291752,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('Camellia','Pylant','CamelliaPylant@gmail.com',9947713617,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('abhi','p','abhip@gmail.com',9906567323,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('ram','chunduri','ramchunduri@gmail.com',9914056931,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('Hayley','chowdary','Hayleychowdary@gmail.com',9978202970,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('Norah','reddy','Norahreddy@gmail.com',9905745831,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('Rosina','kumar','Rosinakumar@gmail.com',9902541196,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('Royal','siddi','Royalsiddi@gmail.com',9986385421,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('swapna','shetty','swapnashetty@gmail.com',9968864068,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('ishaan','vanam','ishaanvanam@gmail.com',9978426695,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('bala','kommula','balakommula@gmail.com',9904662956,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('dilip','tanneri','diliptanneri@gmail.com',9934903616,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('harsha','lakkireddy','harshalakkireddy@gmail.com',9920620738,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('ganesh','kanaka','ganeshkanaka@gmail.com',9952666046,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('damodar','katepally','damodarkatepally@gmail.com',9969238399,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('prasad','yadav','prasadyadav@gmail.com',9947136034,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('neeraj','goud','neerajgoud@gmail.com',9985013469,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('ranjith','Ploszaj','ranjithPloszaj@gmail.com',9940420737,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('rama','siddi','ramasiddi@gmail.com',9972402520,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('raj','shetty','rajshetty@gmail.com',9935449691,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('venu','vanam','venuvanam@gmail.com',9950833426,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('sree','kommula','sreekommula@gmail.com',9957206999,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('deepak','tanneri','deepaktanneri@gmail.com',9924840839,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('jeevan','lakkireddy','jeevanlakkireddy@gmail.com',9954056018,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('pratap','kanaka','pratapkanaka@gmail.com',9912585317,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('manoj','katepally','manojkatepally@gmail.com',9921643206,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('praveen','yadav','praveenyadav@gmail.com',9918724831,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('jaswanth','goud','jaswanthgoud@gmail.com',9968516331,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('yaswanth','vani','yaswanthvani@gmail.com',9964414828,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('rajesh','gotti','rajeshgotti@gmail.com',9926472819,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('rakesh','mukkla','rakeshmukkla@gmail.com',9929679826,'JOB_SEEKER');
INSERT INTO user(first_name,last_name,email,mobile,role) VALUES ('manish','ambati','manishambati@gmail.com',9964172740,'JOB_SEEKER');






INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (1,25,1,NULL,59,'suriya','M','Degree',9.12138E+11,'AADHAAR',1,'rani',1,3343434,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (2,25,0,NULL,49,'nookiya','F','Intermediate',6.45582E+11,'AADHAAR',1,'swetha',0,3343435,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (3,28,0,NULL,80,'byreddy sridhar','M','SSC',9.27338E+11,'AADHAAR',0,'vani',1,3343436,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (4,21,1,NULL,64,'chaitanya','F','SSC',6.31424E+11,'AADHAAR',0,'bhavani',0,3343437,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (5,22,0,NULL,75,'munnar','M','Btech',8.20536E+11,'AADHAAR',0,'rani',0,3343438,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (6,20,0,NULL,52,'mani','F','BA',9.08775E+11,'AADHAAR',0,'soni',1,3343439,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (7,19,1,NULL,48,'gani','M','Degree',7.26254E+11,'AADHAAR',0,'mallamma',0,3343440,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (8,21,0,NULL,66,'goutham','F','LLB',7.43409E+11,'AADHAAR',0,'venkatmma',1,3343441,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (9,22,0,NULL,79,'mallaya','M','Degree',6.83529E+11,'AADHAAR',1,'chandana',1,3343442,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (10,24,0,NULL,52,'rani','F','Intermediate',8.62839E+11,'AADHAAR',1,'kumari',1,3343443,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (11,28,1,NULL,59,'munnar','M','SSC',7.5186E+11,'AADHAAR',1,'rajini',0,3343444,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (12,21,0,NULL,61,'kumar','F','Degree',9.83247E+11,'AADHAAR',0,'sreevani',0,3343445,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (13,23,0,NULL,77,'reddy','M','Intermediate',6.30957E+11,'AADHAAR',1,'rani',0,3343446,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (14,34,0,NULL,47,'chowdari','F','SSC',8.46309E+11,'AADHAAR',1,'divi',0,3343447,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (15,32,1,NULL,50,'hanuman sri','M','SSC',7.74382E+11,'AADHAAR',1,'swetha',0,3343448,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (16,22,0,NULL,76,'depak','F','Btech',7.68176E+11,'AADHAAR',1,'swathi',0,3343449,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (17,21,0,NULL,64,'ramesh','M','BA',7.80795E+11,'AADHAAR',0,'sameera',1,3343450,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (18,20,1,NULL,48,'jeenani','F','Degree',8.80309E+11,'AADHAAR',1,'shaiki',0,3343451,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (19,24,0,NULL,48,'rannai','M','Degree',6.4395E+11,'AADHAAR',1,'skakthi',0,3343452,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (20,20,0,NULL,45,'srinivas','F','Degree',7.48715E+11,'AADHAAR',1,'anuoama',0,3343453,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (21,22,1,NULL,71,'vani','M','Intermediate',6.73817E+11,'AADHAAR',1,'soujanya',1,3343454,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (22,21,0,NULL,80,'venu','F','SSC',7.20134E+11,'AADHAAR',0,'raagini',0,3343455,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (23,28,0,NULL,72,'hanuman sri','M','SSC',8.90608E+11,'AADHAAR',0,'naga',1,3343456,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (24,31,1,NULL,47,'maru','F','Degree',9.35286E+11,'AADHAAR',0,'jothi',1,3343457,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (25,30,0,NULL,61,'charu','M','BA',7.68855E+11,'AADHAAR',1,'vijaya',1,3343458,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (26,17,0,NULL,58,'rajesh','F','Degree',6.94167E+11,'AADHAAR',0,'soni',1,3343459,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (27,21,1,NULL,48,'sampath','M','LLB',7.86188E+11,'AADHAAR',0,'mallamma',0,3343460,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (28,26,0,NULL,72,'venkatesh','F','Degree',9.23964E+11,'AADHAAR',0,'venkatmma',0,3343461,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (29,24,0,NULL,61,'soma','M','Intermediate',7.45366E+11,'AADHAAR',0,'chandana',1,3343462,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (30,34,1,NULL,72,'venkatesh','F','SSC',8.91452E+11,'AADHAAR',0,'kumari',1,3343463,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (31,34,0,NULL,76,'phanendra','M','Degree',7.26055E+11,'AADHAAR',0,'rajini',1,3343464,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (32,34,0,NULL,66,'juturi','F','Intermediate',7.89343E+11,'AADHAAR',1,'sreevani',0,3343465,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (33,18,1,NULL,59,'sunil','M','SSC',9.7804E+11,'AADHAAR',1,'rani',0,3343466,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (34,32,0,NULL,75,'mllaya','F','SSC',7.56912E+11,'AADHAAR',0,'tina',1,3343467,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (35,18,0,NULL,58,'ankarao','M','Btech',7.76662E+11,'AADHAAR',1,'mariyamma',1,3343468,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (36,23,1,NULL,51,'pahni','F','BA',6.85583E+11,'AADHAAR',0,'sunitha',0,3343469,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (37,18,0,NULL,73,'ghani','M','Degree',7.81765E+11,'AADHAAR',1,'jecintha',1,3343470,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (38,17,0,NULL,52,'somu','F','Degree',8.83507E+11,'AADHAAR',1,'soujanya',0,3343471,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (39,25,1,NULL,59,'rakesh','M','Degree',9.90781E+11,'AADHAAR',0,'raagini',0,3343472,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (40,21,0,NULL,59,'rajesh','F','Intermediate',7.00755E+11,'AADHAAR',1,'naga',1,3343473,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (41,19,0,NULL,71,'mallya','M','Degree',6.40987E+11,'AADHAAR',0,'jothi',1,3343474,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (42,17,1,NULL,54,'srinivas','F','Degree',6.75481E+11,'AADHAAR',1,'vijaya',1,3343475,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (43,28,0,NULL,68,'srinu','M','Intermediate',6.68002E+11,'AADHAAR',0,'soni',0,3343476,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (44,22,0,NULL,79,'raju','F','SSC',7.20632E+11,'AADHAAR',1,'mallamma',1,3343477,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (45,24,0,NULL,78,'raman','M','SSC',9.76402E+11,'AADHAAR',1,'venkatmma',1,3343478,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (46,32,1,NULL,56,'narayana','F','Degree',9.70961E+11,'AADHAAR',0,'chandana',1,3343479,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (47,34,0,NULL,58,'sai babau','M','BA',8.33673E+11,'AADHAAR',1,'kumari',1,3343480,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (48,34,0,NULL,52,'babai','F','BA',7.05707E+11,'AADHAAR',1,'nagamma',1,3343481,NULL,NULL);



