INSERT INTO category(name) VALUES ('Agriculture');
INSERT INTO category(name) VALUES ('Apparel');
INSERT INTO category(name) VALUES ('Automotive');
INSERT INTO category(name) VALUES ('Banking');
INSERT INTO category(name) VALUES ('Beauty & Wellness');
INSERT INTO category(name) VALUES ('Construction');
INSERT INTO category(name) VALUES ('Electronics & Hardware');
INSERT INTO category(name) VALUES ('Employability Enhancer');
INSERT INTO category(name) VALUES ('Furniture & Fittings');
INSERT INTO category(name) VALUES ('Gems & Jewellery');
INSERT INTO category(name) VALUES ('Green Jobs');
INSERT INTO category(name) VALUES ('Healthcare');
INSERT INTO category(name) VALUES ('Hydrocarbons');
INSERT INTO category(name) VALUES ('Instructional / Learning Strategies');
INSERT INTO category(name) VALUES ('Instrumentation');
INSERT INTO category(name) VALUES ('IT-ITES');
INSERT INTO category(name) VALUES ('Life Sciences');
INSERT INTO category(name) VALUES ('Logistics');
INSERT INTO category(name) VALUES ('Management - Security');
INSERT INTO category(name) VALUES ('Management and Entrepreneurship');
INSERT INTO category(name) VALUES ('Media & Entertainment');
INSERT INTO category(name) VALUES ('Other');
INSERT INTO category(name) VALUES ('People with Disability');
INSERT INTO category(name) VALUES ('Plumbing');
INSERT INTO category(name) VALUES ('Power');
INSERT INTO category(name) VALUES ('Retail');
INSERT INTO category(name) VALUES ('Rubber');
INSERT INTO category(name) VALUES ('Strategic Manufacturing');
INSERT INTO category(name) VALUES ('Telecom');
INSERT INTO category(name) VALUES ('TEST11');
INSERT INTO category(name) VALUES ('Textiles & Handlooms');
INSERT INTO category(name) VALUES ('Tourism & Hospitality');

INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Rebbecca','Didio',381749123,'rebbecca.didio@didio.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Stevie','Hallo',799973366,'stevie.hallo@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Mariko','Stayer',855589019,'mariko_stayer@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Gerardo','Woodka',260444682,'gerardo_woodka@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Mayra','Bena',214556085,'mayra.bena@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Idella','Scotland',878681355,'idella@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Sherill','Klar',865228931,'sklar@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Ena','Desjardiws',252269402,'ena_desjardiws@desjardiws.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Vince','Siena',731849989,'vince_siena@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Theron','Jarding',868904661,'tjarding@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Amira','Chudej',781353271,'amira.chudej@chudej.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Marica','Tarbor',311746817,'marica.tarbor@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Shawna','Albrough',779776039,'shawna.albrough@albrough.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Paulina','Maker',883448929,'paulina_maker@maker.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Rose','Jebb',749419471,'rose@jebb.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Reita','Tabar',235187078,'rtabar@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Maybelle','Bewley',793877293,'mbewley@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Camellia','Pylant',251714345,'camellia_pylant@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Roy','Nybo',253117778,'rnybo@nybo.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Albert','Sonier',793542612,'albert.sonier@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Hayley','Taghon',216384380,'htaghon@taghon.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Norah','Daleo',253226127,'ndaleo@daleo.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Rosina','Sidhu',764604488,'rosina_sidhu@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Royal','Costeira',753386357,'royal_costeira@costeira.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Barrie','Nicley',364432786,'bnicley@nicley.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Linsey','Gedman',747853781,'lgedman@gedman.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Laura','Bourbonnais',365436688,'laura.bourbonnais@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Fanny','Stoneking',737219123,'fstoneking@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Kristian','Ellerbusch',827481250,'kristian@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Gwen','Julye',370636734,'gjulye@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Ben','Majorga',281719051,'ben.majorga@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Trina','Oto',711538567,'trina@oto.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Emelda','Geffers',870973947,'emelda.geffers@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Zana','Ploszaj',779918880,'zana_ploszaj@ploszaj.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Shaun','Rael',389985485,'shaun.rael@rael.com.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Oren','Lobosco',250461307,'olobosco@hotmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Catherin','Aguele',764761399,'caguele@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Pearlene','Boudrie',744637223,'pboudrie@boudrie.net.au');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Kathryn','Bonalumi',830712258,'kathryn.bonalumi@yahoo.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Suzan','Landa',715761412,'suzan.landa@gmail.com');
INSERT INTO user(first_name,last_name,mobile,email) VALUES ('Sommer','Agar',891303372,'sagar@agar.net.au');

INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('praveeenreddy@gmail.com','Praveeen','Reddy',9895967968,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('balashowry@gmail.com','Bala','Showry',9997627269,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('jaykumari@gmail.com','Jay','Kumari',9949841485,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('sudheerraj@gmail.com','Sudheer','Raj',9950707760,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('samruth@gmail.com','Sam','Ruth',9915331253,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('swapnakumari@gmail.com','Swapna','Kumari',9949525353,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ishaanraj@gmail.com','Ishaan','Raj',9899541142,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('balasunder@gmail.com','Bala','Sunder',9984821228,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('dilippravi@gmail.com','Dilip','Pravi',9967123671,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('harshamodu@gmail.com','Harsha','Modu',9926908828,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ganeshvaranasi@gmail.com','Ganesh','Varanasi',9971477669,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('damodaralla@gmail.com','Damodar','Alla',9935781900,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('prasadpasa@gmail.com','Prasad','Pasa',9924912129,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('neerajreddy@gmail.com','Neeraj','Reddy',9999696962,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ranjithyeryva@gmail.com','Ranjith','Yeryva',9897152722,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('siva vadlamudi@gmail.com','Siva','Vadlamudi',9908446717,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('katepallihemanth@gmail.com','Katepalli','Hemanth',9955291752,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('camelliapylant@gmail.com','Camellia','Pylant',9947713617,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('abhip@gmail.com','Abhi','P',9906567323,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ramchunduri@gmail.com','Ram','Chunduri',9914056931,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('hayleychowdary@gmail.com','Hayley','Chowdary',9978202970,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('norahreddy@gmail.com','Norah','Reddy',9905745831,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('rosinakumar@gmail.com','Rosina','Kumar',9902541196,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('royalsiddi@gmail.com','Royal','Siddi',9986385421,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('swapnashetty@gmail.com','Swapna','Shetty',9968864068,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ishaanvanam@gmail.com','Ishaan','Vanam',9978426695,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('balakommula@gmail.com','Bala','Kommula',9904662956,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('diliptanneri@gmail.com','Dilip','Tanneri',9934903616,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('harshalakkireddy@gmail.com','Harsha','Lakkireddy',9920620738,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ganeshkanaka@gmail.com','Ganesh','Kanaka',9952666046,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('damodarkatepally@gmail.com','Damodar','Katepally',9969238399,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('prasadyadav@gmail.com','Prasad','Yadav',9947136034,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('neerajgoud@gmail.com','Neeraj','Goud',9985013469,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ranjithploszaj@gmail.com','Ranjith','Ploszaj',9940420737,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('ramasiddi@gmail.com','Rama','Siddi',9972402520,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('rajshetty@gmail.com','Raj','Shetty',9935449691,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('venuvanam@gmail.com','Venu','Vanam',9950833426,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('sreekommula@gmail.com','Sree','Kommula',9957206999,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('deepaktanneri@gmail.com','Deepak','Tanneri',9924840839,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('jeevanlakkireddy@gmail.com','Jeevan','Lakkireddy',9954056018,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('pratapkanaka@gmail.com','Pratap','Kanaka',9912585317,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('manojkatepally@gmail.com','Manoj','Katepally',9921643206,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('praveenyadav@gmail.com','Praveen','Yadav',9918724831,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('jaswanthgoud@gmail.com','Jaswanth','Goud',9968516331,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('yaswanthvani@gmail.com','Yaswanth','Vani',9964414828,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('rajeshgotti@gmail.com','Rajesh','Gotti',9926472819,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('rakeshmukkla@gmail.com','Rakesh','Mukkla',9929679826,'JOB_SEEKER');
INSERT INTO user(email,first_name,last_name,mobile,role) VALUES ('manishambati@gmail.com','Manish','Ambati',9964172740,'JOB_SEEKER');


INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (1,25,1,NULL,59,'suriya','M','Degree',9.12138E+11,'AADHAAR',1,'rani',1,3343434,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (2,25,0,NULL,49,'nookiya','F','Intermediate',6.45582E+11,'AADHAAR',1,'swetha',0,3343435,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (3,28,0,NULL,80,'byreddy sridhar','M','SSC',9.27338E+11,'AADHAAR',0,'vani',1,3343436,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (4,21,1,NULL,64,'chaitanya','F','SSC',6.31424E+11,'AADHAAR',0,'bhavani',0,3343437,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (5,22,0,NULL,75,'munnar','M','Btech',8.20536E+11,'AADHAAR',0,'rani',0,3343438,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (6,20,0,NULL,52,'mani','F','BA',9.08775E+11,'AADHAAR',0,'soni',1,3343439,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (7,19,1,NULL,48,'gani','M','Degree',7.26254E+11,'AADHAAR',0,'mallamma',0,3343440,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (8,21,0,NULL,66,'goutham','F','LLB',7.43409E+11,'AADHAAR',0,'venkatmma',1,3343441,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (9,22,0,NULL,79,'mallaya','M','Degree',6.83529E+11,'AADHAAR',1,'chandana',1,3343442,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (10,24,0,NULL,52,'rani','F','Intermediate',8.62839E+11,'AADHAAR',1,'kumari',1,3343443,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (11,28,1,NULL,59,'munnar','M','SSC',7.5186E+11,'AADHAAR',1,'rajini',0,3343444,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (12,21,0,NULL,61,'kumar','F','Degree',9.83247E+11,'AADHAAR',0,'sreevani',0,3343445,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (13,23,0,NULL,77,'reddy','M','Intermediate',6.30957E+11,'AADHAAR',1,'rani',0,3343446,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (14,34,0,NULL,47,'chowdari','F','SSC',8.46309E+11,'AADHAAR',1,'divi',0,3343447,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (15,32,1,NULL,50,'hanuman sri','M','SSC',7.74382E+11,'AADHAAR',1,'swetha',0,3343448,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (16,22,0,NULL,76,'depak','F','Btech',7.68176E+11,'AADHAAR',1,'swathi',0,3343449,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (17,21,0,NULL,64,'ramesh','M','BA',7.80795E+11,'AADHAAR',0,'sameera',1,3343450,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (18,20,1,NULL,48,'jeenani','F','Degree',8.80309E+11,'AADHAAR',1,'shaiki',0,3343451,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (19,24,0,NULL,48,'rannai','M','Degree',6.4395E+11,'AADHAAR',1,'skakthi',0,3343452,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (20,20,0,NULL,45,'srinivas','F','Degree',7.48715E+11,'AADHAAR',1,'anuoama',0,3343453,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (21,22,1,NULL,71,'vani','M','Intermediate',6.73817E+11,'AADHAAR',1,'soujanya',1,3343454,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (22,21,0,NULL,80,'venu','F','SSC',7.20134E+11,'AADHAAR',0,'raagini',0,3343455,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (23,28,0,NULL,72,'hanuman sri','M','SSC',8.90608E+11,'AADHAAR',0,'naga',1,3343456,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (24,31,1,NULL,47,'maru','F','Degree',9.35286E+11,'AADHAAR',0,'jothi',1,3343457,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (25,30,0,NULL,61,'charu','M','BA',7.68855E+11,'AADHAAR',1,'vijaya',1,3343458,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (26,17,0,NULL,58,'rajesh','F','Degree',6.94167E+11,'AADHAAR',0,'soni',1,3343459,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (27,21,1,NULL,48,'sampath','M','LLB',7.86188E+11,'AADHAAR',0,'mallamma',0,3343460,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (28,26,0,NULL,72,'venkatesh','F','Degree',9.23964E+11,'AADHAAR',0,'venkatmma',0,3343461,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (29,24,0,NULL,61,'soma','M','Intermediate',7.45366E+11,'AADHAAR',0,'chandana',1,3343462,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (30,34,1,NULL,72,'venkatesh','F','SSC',8.91452E+11,'AADHAAR',0,'kumari',1,3343463,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (31,34,0,NULL,76,'phanendra','M','Degree',7.26055E+11,'AADHAAR',0,'rajini',1,3343464,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (32,34,0,NULL,66,'juturi','F','Intermediate',7.89343E+11,'AADHAAR',1,'sreevani',0,3343465,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (33,18,1,NULL,59,'sunil','M','SSC',9.7804E+11,'AADHAAR',1,'rani',0,3343466,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (34,32,0,NULL,75,'mllaya','F','SSC',7.56912E+11,'AADHAAR',0,'tina',1,3343467,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (35,18,0,NULL,58,'ankarao','M','Btech',7.76662E+11,'AADHAAR',1,'mariyamma',1,3343468,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (36,23,1,NULL,51,'pahni','F','BA',6.85583E+11,'AADHAAR',0,'sunitha',0,3343469,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (37,18,0,NULL,73,'ghani','M','Degree',7.81765E+11,'AADHAAR',1,'jecintha',1,3343470,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (38,17,0,NULL,52,'somu','F','Degree',8.83507E+11,'AADHAAR',1,'soujanya',0,3343471,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (39,25,1,NULL,59,'rakesh','M','Degree',9.90781E+11,'AADHAAR',0,'raagini',0,3343472,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (40,21,0,NULL,59,'rajesh','F','Intermediate',7.00755E+11,'AADHAAR',1,'naga',1,3343473,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (41,19,0,NULL,71,'mallya','M','Degree',6.40987E+11,'AADHAAR',0,'jothi',1,3343474,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (42,17,1,NULL,54,'srinivas','F','Degree',6.75481E+11,'AADHAAR',1,'vijaya',1,3343475,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (43,28,0,NULL,68,'srinu','M','Intermediate',6.68002E+11,'AADHAAR',0,'soni',0,3343476,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (44,22,0,NULL,79,'raju','F','SSC',7.20632E+11,'AADHAAR',1,'mallamma',1,3343477,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (45,24,0,NULL,78,'raman','M','SSC',9.76402E+11,'AADHAAR',1,'venkatmma',1,3343478,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (46,32,1,NULL,56,'narayana','F','Degree',9.70961E+11,'AADHAAR',0,'chandana',1,3343479,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (47,34,0,NULL,58,'sai babau','M','BA',8.33673E+11,'AADHAAR',1,'kumari',1,3343480,NULL,NULL);
INSERT INTO student(id,age,counselling,course,exams_percentage,father_name,gender,highest_qualification,id_number,id_proof,interview,mother_name,placement,registration_number,skill,student_type) VALUES (48,34,0,NULL,52,'babai','F','BA',7.05707E+11,'AADHAAR',1,'nagamma',1,3343481,NULL,NULL);

INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (1, 'Mon-Fri', 'This AI for Medical Diagnosis program offered by Coursera in partnership with Deeplearning is part of the AI for Medicine Specialization.', 15, 0, 'Medical Diagnosis', '- Disease detection with computer vision - Evaluating models - FImage segmentation on MRI images');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (2, 'Mon-Fri', 'Newborn Baby care skills . Gain skills in newborn baby care, safety, & health including breastfeeding, safe sleep, & screenings with this Newborn Baby Care offered by Coursera in partnership with University of Colorado System.', 120, 0, 'Newborn Baby Care', '- Preventative Healthcare for the Newborn Baby - The Newborn Assessment - Guidance to Keep Newborn Babies Safe and Healthy - Supporting Parents of a Newborn Baby - Newborn Capstone');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (3, 'Mon-Fri', 'In this Positive Psychiatry and Mental Health course offered by Coursera in partnership with The University of Sydney, we will explore different aspects of good mental health as well as provide an overview of the major kinds of mental disorders, their causes, treatments and how to seek help and support.', 20, 0, 'Psychiatry and Mental Health', '- Positive mental health and Psychiatry - Body and Mind - Love and Work - Mental Illness - Paths to Recovery');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (4, 'Mon-Fri', 'The modules of the Dental Assistant course from International Open Academy have been created to help you better understand both how to enter the field, and what will be expected of you once you do.', 40, 0, 'Dental Assistant', '- Diversity of dental assistants/nurses - Potential for growth - Pre-planning for a career as a dental assistant/nurse');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (5, 'Mon-Fri', 'Begin a rewarding career as a physiotherapy assistant where you can make a meaningful difference in the lives of people in need. Upon completing this Physiotherapy Assistant course from International Open Academy in becoming a physiotherapy assistant', 30, 0, 'Physiotherapy Assistant', '- Duties of a physiotherapist - Specialties within the physiotherapy field - Working with clients with various heath care needs - Ethical responsibilities of the profession');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (6, 'Sat-Sun', 'This Medical Technology and Evaluation offered by Coursera in partnership with University of Minnesota is part of the Healthcare Marketplace Specialization.', 20, 0, 'Technology and Evaluation', '- Clinical Trials and Insurance Claims Data - The Elements of Medical Technology Assessments - Methodological Approaches and Considerations');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (7, 'Mon-Fri', 'Are you keen to take your nursing career to a higher level? This 100% online and part-time Nursing short course from University of Essex Online is designed for practicing nurses who want to continue their professional development.', 160, 0, 'Nursing', '- Healthcare Management: Principles and Practices - Healthcare Leadership in Practice - Diabetes: Prevention, Care and Management - Meeting the Needs of Vulnerable Patients');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (8, 'Sat-Sun', 'EdX is an online learning platform trusted by over 12 million users offering the Food, Nutrition and Health in collaboration with Wageningen University and Research - WageningenX. Learn the truth about food and nutrition.', 80, 0, 'Food, Nutrition and Health', '- Nutrition and Health: Macronutrients and Overnutrition - Nutrition and Health: Micronutrients and Malnutrition');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (10, 'Mon-Fri', 'Beauty & Wellness course aims to provide students with the skills and knowledge to provide a range of beauty and wellness treatments, promote beauty products to client, and handle the daily operation of a salon', 40, 0, 'Makeup Artist', '- Basic Makeup - Basic Nail Care - Basic Facial - Facial & Waxing Treatment');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (11, 'Mon-Fri', 'Hair Fashion & Design course provides students with the skills and knowledge in haircutting, hair perming, hair colouring, hairstyling, hair and scalp care, as well as salon operations and customer service', 60, 0, 'Hair Fashion & Design', '- Shampoo and Head Massage - Basic Haircutting - Basic Hairstyling - Advanced Hair Colouring');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (13, 'Mon-Fri', 'Participants will learn more about the agricultural technologies for food production, farming process and management, urban farming technology and systems, agribusiness and sustainable farming.', 80, 0, 'Urban Agricultural Technology', '- Design, Operation and Management of Urban Farms - Traceability of Farm Produce - Disease: Causes and Identification - Managing the Natural Resource Base for Farming');
INSERT INTO `course` (`id`, `days`, `description`, `duration`, `is_active`, `name`, `syllabus`) VALUES (15, 'Mon-Fri', 'This course is designed for participants to acquire plumbing skills and opportunity to upgrade to Trades Foreman / Tradesman through our training.', 20, 0, 'Plumbing & Pipefitting', '- General Knowledge of Cold water Systems and Plumbing Fittings - General Knowledge of Sanitary Plumbing and Vent Pipe System - Installation of Pipe & Fittings Installation / connection - Installation of Sanitary Fittings - Awareness on safety');