INSERT INTO category(name) VALUES ('Agriculture');
INSERT INTO category(name) VALUES ('Apparel, Made-Ups & Home Furnishing');
INSERT INTO category(name) VALUES ('Automotive');
INSERT INTO category(name) VALUES ('Beauty & Wellness');
INSERT INTO category(name) VALUES ('Banking, Financial Services and Insurance');
INSERT INTO category(name) VALUES ('Construction');
INSERT INTO category(name) VALUES ('Electronics & Hardware');
INSERT INTO category(name) VALUES ('Furniture & Fittings');
INSERT INTO category(name) VALUES ('Gems & Jewellery');
INSERT INTO category(name) VALUES ('Green Jobs');
INSERT INTO category(name) VALUES ('Healthcare');
INSERT INTO category(name) VALUES ('Hydrocarbons');
INSERT INTO category(name) VALUES ('Instrumentation, Automation, Surveillance and Communication');
INSERT INTO category(name) VALUES ('IT-ITES');
INSERT INTO category(name) VALUES ('Life Sciences');
INSERT INTO category(name) VALUES ('Logistics');
INSERT INTO category(name) VALUES ('Management and Entrepreneurship & Professional');
INSERT INTO category(name) VALUES ('Media & Entertainment');
INSERT INTO category(name) VALUES ('Plumbing');
INSERT INTO category(name) VALUES ('Power');
INSERT INTO category(name) VALUES ('Retail');
INSERT INTO category(name) VALUES ('Rubber');
INSERT INTO category(name) VALUES ('Strategic Manufacturing');
INSERT INTO category(name) VALUES ('Telecom');
INSERT INTO category(name) VALUES ('Textiles & Handlooms');
INSERT INTO category(name) VALUES ('Tourism & Hospitality');
INSERT INTO category(name) VALUES ('People with Disability');
INSERT INTO category(name) VALUES ('Management - Security');
INSERT INTO category(name) VALUES ('Other');
INSERT INTO category(name) VALUES ('Employability Enhancer');
INSERT INTO category(name) VALUES ('Instructional / Learning Strategies');
